version: '3'
services:
  nginx:
   container_name: yb-nginx
   image: nginx:latest
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx:/etc/nginx
   - ./log:/var/log/nginx
   depends_on:
   - app

  app:
    restart: always
    image : bum19/dockerdeployproject:1.0
    expose:
      - "8080"
